version: '3'
services:
  database:
    image: postgres:14-alpine
    container_name: database_test_igma
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: test_backend_igma
    build: .
    ports:
      - 5000:5000
    depends_on:
      - database
    env_file:
      - .env

volumes:
  postgres:
